spring.application.name=file-nest

spring.datasource.url=jdbc:mysql://localhost:3306/file_nest
spring.datasource.username=filenest_user32
spring.datasource.password=4343

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=file-nest-super-secret-jwt-key-2026
jwt.expiration=86400000

# CREATE USER 'filenest_user32'@'localhost'
# IDENTIFIED BY '4343';CREATE USER 'filenest_user32'@'localhost'
# IDENTIFIED BY '4343';